import { ICoursesData } from "./CoursesState";

export const COURSE_DATA: ICoursesData = {
  "Cálculo Integral": {
    pc: {
      count: 4,
      deleteCount: 1,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    pd: {
      count: 4,
      deleteCount: 1,
      weight: 0.1,
      precision: 1,
      fixed: false,
      round: false,
    },
    parcial: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    final: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    _: {
      precision: 1,
      fixed: false,
      round: false,
    },
  },
  "Cálculo en Varias Variables": {
    pc: {
      count: 4,
      deleteCount: 1,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    pd: {
      count: 4,
      deleteCount: 1,
      weight: 0.1,
      precision: 1,
      fixed: false,
      round: false,
    },
    parcial: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    final: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    _: {
      precision: 1,
      fixed: false,
      round: false,
    },
  },
  "Diseño digital": {
    lab: {
      count: 10,
      deleteCount: 1,
      weight: 0.2,
      precision: 1,
      fixed: false,
      round: false,
    },
    tarea: {
      count: 1,
      deleteCount: 0,
      weight: 0.2,
      precision: 1,
      fixed: false,
      round: false,
    },
    parcial: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    final: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    _: {
      precision: 1,
      fixed: false,
      round: false,
    },
  },

  "Física 2": {
    pc: {
      count: 4,
      deleteCount: 1,
      weight: 0.4,
      precision: 1,
      fixed: false,
      round: false,
    },
    parcial: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    final: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    _: {
      precision: 1,
      fixed: false,
      round: false,
    },
  },

  "Lab Física": {
    labs: {
      count: 6,
      deleteCount: 1,
      weight: 1,
      precision: 1,
      fixed: false,
      round: false,
    },
    _: {
      precision: 1,
      fixed: false,
      round: false,
    },
  },

  psicologia: {
    participación: {
      count: 1,
      deleteCount: 0,
      weight: 0.1,
      precision: 1,
      fixed: false,
      round: false,
    },
    permanete: {
      count: 4,
      deleteCount: 0,
      weight: 0.4,
      precision: 1,
      fixed: false,
      round: false,
    },
    parcial: {
      count: 1,
      deleteCount: 0,
      weight: 0.2,
      precision: 1,
      fixed: false,
      round: false,
    },
    oral: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    _: {
      precision: 1,
      fixed: false,
      round: false,
    },
  },
  "Estructuras Discretas": {
    pc: {
      count: 4,
      deleteCount: 1,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    parical: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    final: {
      count: 1,
      deleteCount: 0,
      weight: 0.4,
      precision: 1,
      fixed: false,
      round: false,
    },
    _: {
      precision: 1,
      fixed: false,
      round: false,
    },
  },
  "Fundamentos de Programación": {
    PC: {
      count: 10,
      deleteCount: 1,
      weight: 0.5,
      precision: 1,
      fixed: false,
      round: false,
    },
    Exa1: {
      count: 1,
      deleteCount: 0,
      weight: 0.2,
      precision: 1,
      fixed: false,
      round: false,
    },
    Exa2: {
      count: 1,
      deleteCount: 0,
      weight: 0.3,
      precision: 1,
      fixed: false,
      round: false,
    },
    _: {
      precision: 1,
      fixed: false,
      round: true,
    },
  },
};
